<!DOCTYPE html>
<html>
 <head>
   <title>管理系统</title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <meta http-equiv="Cache-Control"/> 
   <meta name="robots" content="none">
   <meta name="HandheldFriendly" content="True">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
   <style type="text/css">
        .el-menu-demo{
	       position: fixed;
        	top:0px;
        	width:100%;
        }
        .main{
	       position: absolute;
        	top:81px;
        	left:220px;
        }
        #sidebar{
        	position:absolute;
        	top:61px;
        }
   </style>
 </head>
<body>
<div id="app">
