<!DOCTYPE html>
<html>
 <head>
   <title>管理系统</title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <meta http-equiv="Cache-Control"/> 
   <meta name="robots" content="none">
   <meta name="HandheldFriendly" content="True">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
   <style type="text/css">
        .el-menu-demo{
        	box-shadow: 0 2px 8px #f0f1f2;
        	text-align: center;
        }
        body{margin: 0px; padding: 0px;}
        .container{
        	width:80%;
        	margin:0px auto;
        	height: 100%;
        }
        .container .main{width:70%;}
        .container .aside{width:28%;}
        .container .main li{
        	list-style: none;
	        border-bottom: 1px solid #f2f2f2;
        }
        .container .main li a{
	       text-decoration: none;
        	color:#000;
        }
        .el-carousel__item h3 {
            color: #475669;
            font-size: 18px;
            opacity: 0.75;
            line-height: 300px;
            margin: 0;
        }
          
        .el-carousel__item:nth-child(2n) {
            background-color: #99a9bf;
        }
          
        .el-carousel__item:nth-child(2n+1) {
            background-color: #d3dce6;
        }
    </style>
 </head>
<body>
<div id="app">
<el-menu :default-active="activeIndex" class="el-menu-demo" mode="horizontal" @select="handleSelect">
  <el-menu-item index="0">首页</el-menu-item>
  <el-menu-item index="1">处理中心</el-menu-item>
  <el-submenu index="2">
    <template slot="title">我的工作台</template>
    <el-menu-item index="2-1">选项1</el-menu-item>
    <el-menu-item index="2-2">选项2</el-menu-item>
    <el-menu-item index="2-3">选项3</el-menu-item>
    <el-submenu index="2-4">
      <template slot="title">选项4</template>
      <el-menu-item index="2-4-1">选项1</el-menu-item>
      <el-menu-item index="2-4-2">选项2</el-menu-item>
      <el-menu-item index="2-4-3">选项3</el-menu-item>
    </el-submenu>
  </el-submenu>
  <el-menu-item index="3" disabled>消息中心</el-menu-item>
  <el-menu-item index="4"><a href="https://www.ele.me" target="_blank">订单管理</a></el-menu-item>
</el-menu>
<div class="line"></div>
