<?php include Yaf\View\Simple::getScriptPath().'/commom/header.phtml';?>
<?php include Yaf\View\Simple::getScriptPath().'/commom/top.phtml';?>
<div class="container main">
	<el-breadcrumb separator-class="el-icon-arrow-right">
      <el-breadcrumb-item :to="{ path: '/' }">首页</el-breadcrumb-item>
      <el-breadcrumb-item>活动管理</el-breadcrumb-item>
      <el-breadcrumb-item>活动列表</el-breadcrumb-item>
      <el-breadcrumb-item>活动详情</el-breadcrumb-item>
    </el-breadcrumb>
</div>
<?php include Yaf\View\Simple::getScriptPath().'/commom/footer.phtml';?>